= cnd.nextapt

The link:cnd.apt.antlr4[] directory contains an Antlr4 Lexer Grammar that may be a
replacement to NetBeans 8.2 "cnd.apt" link:cnd.apt.nb82/aptlexer.g[aptlexer.g], that
was implemented on top of the "cnd.antlr" runtime (a fork of Antlr v2.7.7).

This projects contains link:cnd.apt.nb82/nb82/org/netbeans/netbeans82/[some jar files]
from the NetBeans 8.2 IDE, possibly released under the CDDL License.

== Install

[source, bash]
----
mvn clean install
----

== Run NB8.2 Lexer

To run the NB8.2 lexer and generate an XML file with the tokens (that will be placed near the input file).

[source, bash]
----
java -jar cnd.apt.nb82/target/cnd.apt.nb82-1.0-SNAPSHOT-jar-with-dependencies.jar input.[ch]
----

== Run the Antlr4 lexer

To run the Antlr4 powered lexer, issue the following command:

[source, bash]
----
cnd.apt.antlr4/target/cnd.apt.antlr4-1.0-SNAPSHOT-jar-with-dependencies.jar input.[ch]
----

This will print out the lexer tokens on stdout.

== License

This is APLv2. See link:LICENSE[LICENSE] for details.

The NetBeans 8.2 binaries are (C) Oracle Corporation, possibly covered by the CDDL-1.0 / GPL+CPE license.


