= cnd.nextapt

The link:cnd.apt.antlr4[] directory contains an Antlr4 Lexer Grammar that may be a
replacement to NetBeans 8.2 "cnd.apt" link:cnd.apt.nb82/aptlexer.g[aptlexer.g], that
was implemented on top of the "cnd.antlr" runtime (a fork of Antlr v2.7.7).

This projects contains link:cnd.apt.nb82/nb82/org/netbeans/netbeans82/[some jar files]
from the NetBeans 8.2 IDE, possibly released under the CDDL License.

== Install

[source, bash]
----
mvn clean install
----

== Run NB8.2 Lexer

To run the NB8.2 lexer, run the following command:

[source, bash]
----
$ cd cnd.apt.nb82
$ java -Dlexer.print=false -jar target/cnd.apt.nb82-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/include/
----

This will read all `*.h/*.c` files in /usr/include and will report some performance information, like so:

[source, bash]
----
Processed 200 files in  0,76 seconds (2,6e+02 files/second 4,2e+03 Mb/second).
----

== Run the Antlr4 lexer

To run the Antlr4 powered lexer, run the following command:

[source, bash]
----
$ cd cnd.apt.antlr4
$ java -Dlexer.print=false -jar target/cnd.apt.antlr4-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/include/
----

This will read all `*.h/*.c` files in /usr/include and will report some performance information, like so:

[source, bash]
----
Processed 200 files in  0,50 seconds (4,0e+02 files/second 6,4e+03 Mb/second).
----

WARNING: If the lexer fails please report the error in the NetBeans @dev mailing list.

If you want to see the lexer modes and tokens then remove the `-Dlexer.print=false` in the command line.


== License

This is APLv2. See link:LICENSE[LICENSE] for details.

The NetBeans 8.2 binaries are (C) Oracle Corporation, possibly covered by the CDDL-1.0 / GPL+CPE license.


